import React, { useState } from 'react';
import { Download, FileText, FileJson, Loader2 } from 'lucide-react';
import { AgentMessage, MarathonTask } from '../types';

interface ExportButtonProps {
  messages: AgentMessage[];
  task: MarathonTask | null;
}

const ExportButton: React.FC<ExportButtonProps> = ({ messages, task }) => {
  const [isExporting, setIsExporting] = useState(false);
  const [showMenu, setShowMenu] = useState(false);

  const exportAsPDF = async () => {
    setIsExporting(true);
    setShowMenu(false);
    
    // Extract generated content from Worker messages
    const workerMessages = messages
      .filter(m => m.agent === 'WORKER' && !m.isRevision && !m.message.includes('Starting Phase'))
      .map(m => m.message)
      .join('\n\n---\n\n');

    // Create PDF content (simplified - in production, use a PDF library)
    const content = `
# ${task?.description || 'Generated Report'}

## Generated Content

${workerMessages}

## Audit Summary

${messages
  .filter(m => m.agent === 'AUDIT')
  .map(m => `- ${m.message.split('\n')[0]}`)
  .join('\n')}

---
Generated by AEGIS Commander
${new Date().toLocaleString()}
    `;

    // Create blob and download
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${task?.description?.substring(0, 30) || 'report'}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setIsExporting(false);
  };

  const exportAsJSON = () => {
    setShowMenu(false);
    const data = {
      task: task,
      messages: messages,
      exportedAt: new Date().toISOString(),
    };
    
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aegis-export-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportAsMarkdown = () => {
    setShowMenu(false);
    let markdown = `# ${task?.description || 'Generated Report'}\n\n`;
    markdown += `**Generated:** ${new Date().toLocaleString()}\n\n`;
    markdown += `## Conversation Flow\n\n`;

    messages.forEach((msg, idx) => {
      markdown += `### ${msg.agent} (Phase ${msg.phase || 'N/A'})\n\n`;
      markdown += `${msg.message}\n\n`;
      if (msg.thoughtTrace) {
        markdown += `*Thought Trace:* ${msg.thoughtTrace}\n\n`;
      }
      markdown += `---\n\n`;
    });

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${task?.description?.substring(0, 30) || 'report'}-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (messages.length === 0) return null;

  return (
    <div className="relative">
      <button
        onClick={() => setShowMenu(!showMenu)}
        disabled={isExporting}
        className="flex items-center gap-2 px-4 py-2 rounded bg-hedera-accent text-black font-bold hover:bg-emerald-400 disabled:opacity-50 transition-all"
      >
        {isExporting ? (
          <>
            <Loader2 className="animate-spin" size={16} />
            Exporting...
          </>
        ) : (
          <>
            <Download size={16} />
            Export
          </>
        )}
      </button>

      {showMenu && (
        <div className="absolute top-full right-0 mt-2 bg-aegis-panel border border-aegis-border rounded-lg shadow-lg z-50 min-w-[180px]">
          <button
            onClick={exportAsPDF}
            className="w-full flex items-center gap-2 px-4 py-2 text-left hover:bg-white/5 transition-colors"
          >
            <FileText size={16} className="text-gray-400" />
            <span className="text-sm text-gray-200">Export as Text</span>
          </button>
          <button
            onClick={exportAsMarkdown}
            className="w-full flex items-center gap-2 px-4 py-2 text-left hover:bg-white/5 transition-colors"
          >
            <FileText size={16} className="text-gray-400" />
            <span className="text-sm text-gray-200">Export as Markdown</span>
          </button>
          <button
            onClick={exportAsJSON}
            className="w-full flex items-center gap-2 px-4 py-2 text-left hover:bg-white/5 transition-colors"
          >
            <FileJson size={16} className="text-gray-400" />
            <span className="text-sm text-gray-200">Export as JSON</span>
          </button>
        </div>
      )}
    </div>
  );
};

export default ExportButton;
